public class GateNot extends LogicGate {
    public GateNot(LogicVariable output, LogicVariable input1) throws Exception{

        if(output.getCalculatedBy() != null)
            throw new ColisionException();

        //Makes sure that the input is not generated by the output variable
        if (input1.getCalculatedBy() != null) {
            LogicVariable[] variablesInput1 = input1.getCalculatedBy().getInputs();
            for (LogicVariable variable : variablesInput1) {
                if (variable.equals(output))
                    throw new CycleException();
            }
        }

        this.output = output;
        this.output.setLogicGate(this);

        this.inputs = new LogicVariable[]{input1};

        this.updateValue();
    }

    @Override
    String getSymbol() {
        return "NOT";
    }

    @Override
    String getFormula() {

        return "NOT(" + this.inputs[0].getFormula() + ")";
    }

    @Override
    void updateValue()
    {
        this.output.setValue(!this.inputs[0].getValue());
    }
}
